---
  - name: Let window ready for dns tests
    tags: [dns]
    shell: |
      tmux send-keys -t "recon/dns" C-z "domain='' && \
      dnsrecon -d $domain | tee {{ project_path }}/dns/dnsrecon.txt \
      && dnsenum $domain | tee {{ project_path }}/dns/dnsenum.txt"
    when: domain == "none"

  - name: Start dns recon
    tags: [dns]
    shell: |
      tmux send-keys -t "recon/dns" C-z "dnsrecon -d {{ domain }} | tee \
      {{ project_path }}/dns/dnsrecon.txt && dnsenum {{ domain }} | tee \
      {{ project_path }}/dns/dnsenum.txt" Enter
    when: domain != "none"