---
  - name: Run gobuster on target
    tags: [web]
    shell: |
      tmux send-keys -t "recon/web" C-z "gobuster dir -u \
      {{ web_protocol }}{{ target }}/ -w \
      /usr/share/dirb/wordlists/big.txt -o \
      {{ project_path }}/web/scan.txt -x .php,.html,.txt" Enter