---
  - name: Run gobuster on target
    shell: |
      set -o pipefail
      tmux send-keys -t "recon/web" C-z "gobuster dir -u \
      {{ web_protocol }}://{{ target }}/ -w \
      /usr/share/dirbuster/wordlists/directory-list-2.3-medium.txt -o \
      {{ project_path }}/web/scan.txt -x .php,.html,.txt" Enter
    register: gobuster
    changed_when: "gobuster.rc != 0"
    tags: [web]