---
  - name: Use snmp-check with public on target
    shell: |
      set -o pipefail
      tmux send-keys -t "enum/snmp" C-z "snmp-check {{ target }} \
      | tee snmp_scan.txt" Enter
    register: snmp_check
    changed_when: "snmp_check.rc != 0"

  - name: Use onesixtyone with default communities on target
    shell: |
      set -o pipefail
      tmux send-keys -t "enum/snmp" "onesixtyone {{ target }} \
      | tee 161.txt" Enter
    register: onesixtyone
    changed_when: "onesixtyone.rc != 0"
