---
  - name: Start tmux in background with given name
    shell: tmux new-session -d -s {{ session_name }}
    tags: [tmux, always]

  - name: Rename first window to debug
    shell: tmux rename-window -t 0 debug
    tags: [tmux, always]

  - name: Enter project folder with debug window
    shell: |
      tmux send-keys -t "debug" C-z "cd {{ project_path }} \
      && clear" Enter

  - name: Create new window named recon/nmap
    shell: tmux new-window -n recon/nmap
    tags: [nmap]

  - name: Create nmap folder
    file:
      path: "{{ project_path +'/nmap' }}"
      state: directory

  - name: Enter project folder with nmap window
    shell: |
      tmux send-keys -t "recon/nmap" C-z "cd {{ project_path }}/nmap \
      && clear" Enter

  - name: Create new window named recon/web
    shell: tmux new-window -n recon/web
    tags: [web]

  - name: Create web folder
    file:
      path: "{{ project_path + '/web' }}"
      state: directory

  - name: Enter project folder with web window
    shell: |
      tmux send-keys -t "recon/web" C-z "cd {{ project_path }}/web \
      && clear" Enter

  - name: Create new window named recon/dns
    shell: tmux new-window -n recon/dns
    tags: [dns]

  - name: Create dns folder
    file:
      path: "{{ project_path + '/dns' }}"
      state: directory

  - name: Enter project folder with dns window
    shell: |
      tmux send-keys -t "recon/dns" C-z "cd {{ project_path }}/dns \
      && clear" Enter

  - name: Create new window named enum/vuln
    shell: tmux new-window -n enum/vuln
    tags: [vuln]
    when: vuln == "true"

  - name: Create vuln folder
    file:
      path: "{{ project_path + '/vuln' }}"
      state: directory
    when: vuln == "true"
    tags: [vuln]

  - name: Enter project folder with vuln window
    shell: |
      tmux send-keys -t "enum/vuln" C-z "cd {{ project_path }}/vuln \
      && clear" Enter
    when: vuln == "true"
    tags: [vuln]

  - name: Create new window named enum/snmp
    shell: tmux new-window -n enum/snmp
    tags: [snmp]

  - name: Create snmp folder
    file:
      path: "{{ project_path + '/snmp' }}"
      state: directory
    tags: [snmp]

  - name: Enter project folder with snmp window
    shell: |
      tmux send-keys -t "enum/snmp" C-z "cd {{ project_path }}/snmp \
      && clear" Enter
    tags: [snmp]

  - name: Create new window named enum/web_vuln
    shell: tmux new-window -n enum/web_vuln
    tags: [web_vuln]
    when: web_vuln == "true"

  - name: Create web_vuln folder
    file:
      path: "{{ project_path + '/web_vuln' }}"
      state: directory
    when: web_vuln == "true"
    tags: [web_vuln]

  - name: Enter project folder with vuln window
    shell: |
      tmux send-keys -t "enum/web_vuln" C-z "cd {{ project_path }}/web_vuln \
      && clear" Enter
    when: web_vuln == "true"
    tags: [web_vuln]